name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js (Fix for Firebase CLI bug)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci
      - run: npm run build

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_SERVICE_ACCOUNT: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > /tmp/firebase-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/firebase-key.json"
          npx firebase-tools deploy --only hosting --project homecaptn
